### ISSUE TITLE
Memeq and memcmp aren't constant time

### ISSUE THREAD

**Issue by Restioson** [quininer/memsec#7]
The comment [here](https://github.com/quininer/memsec/blob/master/src/lib.rs#L30) claims that memeq is constant time. It's really not -- it's Ө(n) where n = len. Same thing for memcmp.

**Comment by quininer** [comment]
You're actually right, but n is usually a constant in cryptography. This name is widely accepted,
for example:

* https://nacl.cr.yp.to/internals.html
* https://download.libsodium.org/doc/internals/#branches
* https://crates.io/crates/constant_time_eq
* https://en.wikipedia.org/wiki/Timing_attack#Examples
* https://cryptocoding.net/index.php/Coding_rules#Compare_secret_strings_in_constant_time

 if you can convince them, I would be happy to change it.

**Comment by Restioson** [comment]
Yeah, but just because lots of people are wrong doesn't mean that you should be wrong too. Maybe say that it is Ө(n) and note that it is non-short circuiting, as this is the correct term (although  Ө(...) does already imply that it is always "constant" time).

**Comment by Restioson** [comment]
Sure, when I have the time. It's still not actually constant time with the const generic...

**Comment by quininer** [comment]
This is the constant time for runtime.

**Comment by quininer** [comment]
In fact, we can use macros to implement it now.

like

```rust
macro_rules! const_memeq {
    ( $b1:expr, $b2:expr, $n:expr ) => {
        fn memeq(b1: *const u8, b2: *const u8) -> bool {
            const N: usize = $n;

            // ...
        }
    }
}
```

**Comment by Restioson** [comment]
@quininer this is still not constant time outright. It just sort of makes it look like it's constant time because it has a constant in it. What this *does* let you do (or rather lets rustc do), however, is unroll the loop, which could be useful too. Nevertheless, it is still algorithmically Ө(n).

**Comment by quininer** [comment]
I mean `const_memeq` is not constant time, but `const_memeq<N>` is constant time.

**Comment by Restioson** [comment]
Although the N is constant, the algorithm which depends on N is not constant.

**Comment by quininer** [comment]
Yes, so I mean `const_memeq<N>` not `const_memeq`. `const_memeq<N>` does not depend on external parameter.

**Comment by Restioson** [comment]
Whether or not it is a constant n parameter is irrelevant. The algorithm still loops n times.
